package dev.deftu.componency.input

public enum class Key(public val char: Char = ' ') {
    KEY_UNKNOWN,
    KEY_ESCAPE,
    KEY_LMETA,
    KEY_RMETA,
    KEY_LCONTROL,
    KEY_RCONTROL,
    KEY_LSHIFT,
    KEY_RSHIFT,
    KEY_LMENU,
    KEY_RMENU,
    KEY_MINUS('-'),
    KEY_EQUALS('='),
    KEY_BACKSPACE,
    KEY_ENTER,
    KEY_TAB,
    KEY_LBRACKET('['),
    KEY_RBRACKET(']'),
    KEY_SEMICOLON(';'),
    KEY_APOSTROPHE('\''),
    KEY_GRAVE('`'),
    KEY_BACKSLASH('\\'),
    KEY_COMMA(','),
    KEY_PERIOD('.'),
    KEY_SLASH('/'),
    KEY_MULTIPLY('*'),
    KEY_SPACE(' '),
    KEY_CAPITAL,
    KEY_LEFT,
    KEY_UP,
    KEY_RIGHT,
    KEY_DOWN,
    KEY_NUMLOCK,
    KEY_SCROLL,
    KEY_SUBTRACT('-'),
    KEY_ADD('+'),
    KEY_DIVIDE('/'),
    KEY_DECIMAL('.'),
    KEY_NUMPAD0,
    KEY_NUMPAD1,
    KEY_NUMPAD2,
    KEY_NUMPAD3,
    KEY_NUMPAD4,
    KEY_NUMPAD5,
    KEY_NUMPAD6,
    KEY_NUMPAD7,
    KEY_NUMPAD8,
    KEY_NUMPAD9,
    KEY_A('A'),
    KEY_B('B'),
    KEY_C('C'),
    KEY_D('D'),
    KEY_E('E'),
    KEY_F('F'),
    KEY_G('G'),
    KEY_H('H'),
    KEY_I('I'),
    KEY_J('J'),
    KEY_K('K'),
    KEY_L('L'),
    KEY_M('M'),
    KEY_N('N'),
    KEY_O('O'),
    KEY_P('P'),
    KEY_Q('Q'),
    KEY_R('R'),
    KEY_S('S'),
    KEY_T('T'),
    KEY_U('U'),
    KEY_V('V'),
    KEY_W('W'),
    KEY_X('X'),
    KEY_Y('Y'),
    KEY_Z('Z'),
    KEY_0('0'),
    KEY_1('1'),
    KEY_2('2'),
    KEY_3('3'),
    KEY_4('4'),
    KEY_5('5'),
    KEY_6('6'),
    KEY_7('7'),
    KEY_8('8'),
    KEY_9('9'),
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_F11,
    KEY_F12,
    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_DELETE,
    KEY_HOME,
    KEY_END;

    public companion object {

        public fun fromChar(char: Char): Key? {
            return values().firstOrNull { key ->
                key.char == char
            }
        }

    }

}
