modLoader="kotlinforforge"
loaderVersion="${forge_loader_version}"
issueTrackerURL="https://github.com/Deftu/${mod_name}/issues"
license="LGPL-3.0-or-later"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="Deftu"
    logoFile="assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
    modId="omnicore"
    mandatory=true
    versionRange="[0.9.0,)"
    ordering="BEFORE"
    side="CLIENT"
